site_name: "Jolly Roger"

theme:
  favicon: assets/logo.png
  name: material
  logo: assets/logo.png
  language: pt
  features:
    - navigation.instant
  palette:
    primary: teal
    accent: teal

nav:
  - Página inicial: index.md
  - Módulo 1: modulo1/mer.md
  - Módulo 2: 
    - Modelo Relacional: modulo2/modelo-relacional.png
    - Legendas do modelo relacional: modulo2/modelo-relacional.png